#pragma once
#include "esp_event.h"

typedef struct {
    void* ptr;
} event_data_wrap_t;

ESP_EVENT_DECLARE_BASE(APP_RECODER_EVENTS);

enum
{
    EVENT_RECODER_START,
    EVENT_RECODER_STOP
};

ESP_EVENT_DECLARE_BASE(APP_WEBSOCKET_EVENTS);

enum
{
    EVENT_SOCKET_OPEN,
    EVENT_SOCKET_CLOSE,
    EVENT_RECORDR_START,
    EVENT_RECORDR_STOP
};

ESP_EVENT_DECLARE_BASE(APP_DISPLAY_EVENTS);

enum
{
    EVENT_UPDATE_MESSAGE,
    EVENT_CREATE_MESSAGE,
    EVENT_SCREEN_ACTIVATE,
    EVENT_SCREEN_DISACTIVATE
};
