// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: whatsder

#ifndef _WHATSDER_UI_H
#define _WHATSDER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "ui_events.h"
#include "ui_helpers.h"
#include "./fonts/ui_font_Chinease.h"

// SCREEN: ui_Screen2
extern uint8_t   recoder_flag;
void             ui_Screen2_screen_init(void);
void             ui_event_Screen2(lv_event_t *e);
extern lv_obj_t *ui_Screen2;
void             ui_event_Screen2Panelcontainer(lv_event_t *e);
extern lv_obj_t *ui_Screen2Panelcontainer;
void             ui_event_Screen2PanelPanel3(lv_event_t *e);
extern lv_obj_t *ui_Screen2PanelPanel3;
extern lv_obj_t *ui_Screen2LabelLabel5;
void             ui_event_Screen2PanelPanel1(lv_event_t *e);
extern lv_obj_t *ui_Screen2PanelPanel1;
extern lv_obj_t *ui_Screen2LabelLabel7;
void             ui_event_Screen2Panelrecode(lv_event_t *e);
extern lv_obj_t *ui_Screen2Panelrecode;
extern lv_obj_t *ui_Screen2LabelLabel3;
// SCREEN: ui_Screen4
void             ui_Screen4_screen_init(void);
void             ui_event_Screen4(lv_event_t *e);
extern lv_obj_t *ui_Screen4;
extern lv_obj_t *ui_Screen4LabelLabel4;
extern lv_obj_t *ui_Screen4ButtonButton13;
extern lv_obj_t *ui_Screen4ButtonButton14;
extern lv_obj_t *ui_Screen4ButtonButton15;
extern lv_obj_t *ui_Screen4ButtonButton16;
// SCREEN: ui_Screen5
void             ui_Screen5_screen_init(void);
void             ui_event_Screen5(lv_event_t *e);
extern lv_obj_t *ui_Screen5;
extern lv_obj_t *ui_Screen5ImageImage2;
// SCREEN: ui_Screen6
void             ui_Screen6_screen_init(void);
void             ui_event_Screen6(lv_event_t *e);
extern lv_obj_t *ui_Screen6;
extern lv_obj_t *ui_Screen6LabelLabel6;
extern lv_obj_t *ui_Screen6ButtonButton21;
extern lv_obj_t *ui_Screen6ButtonButton22;
extern lv_obj_t *ui_Screen6ButtonButton23;
extern lv_obj_t *ui_Screen6ButtonButton24;
// SCREEN: ui_Screen3
void             ui_Screen3_screen_init(void);
void             ui_event_Screen3(lv_event_t *e);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_Screen3LabelLabel1;
extern lv_obj_t *ui_Screen3ButtonButton3;
extern lv_obj_t *ui_Screen3ButtonButton4;
extern lv_obj_t *ui_Screen3ButtonButton5;
extern lv_obj_t *ui_Screen3ButtonButton6;
// SCREEN: ui_Screen1
void             ui_Screen1_screen_init(void);
void             ui_event_Screen1(lv_event_t *e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Screen1LabelLabel2;
extern lv_obj_t *ui_Screen1ButtonButton1;
extern lv_obj_t *ui_Screen1ButtonButton2;
extern lv_obj_t *ui_Screen1ButtonButton7;
extern lv_obj_t *ui_Screen1ButtonButton8;
extern lv_obj_t *ui_Startevents___initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
