// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: whatsder

#include "esp_mesh.h"
#include "ui.h"
#include <stdio.h>

#include "event_declare.h"
#include "../app/event_declare.h"

static char event_code_list[][30] = {
    "LV_EVENT_ALL",
    "LV_EVENT_PRESSED",
    "LV_EVENT_PRESSING",
    "LV_EVENT_PRESS_LOST",
    "LV_EVENT_SHORT_CLICKED",
    "LV_EVENT_LONG_PRESSED",
    "LV_EVENT_LONG_PRESSED_REPEAT",
    "LV_EVENT_CLICKED",
    "LV_EVENT_RELEASED",
    "LV_EVENT_SCROLL_BEGIN",
    "LV_EVENT_SCROLL_END",
    "LV_EVENT_SCROLL",
    "LV_EVENT_GESTURE",
    "LV_EVENT_KEY",
    "LV_EVENT_FOCUSED",
    "LV_EVENT_DEFOCUSED",
    "LV_EVENT_LEAVE",
    "LV_EVENT_HIT_TEST",
    "LV_EVENT_COVER_CHECK",
    "LV_EVENT_REFR_EXT_DRAW_SIZE",
    "LV_EVENT_DRAW_MAIN_BEGIN",
    "LV_EVENT_DRAW_MAIN",
    "LV_EVENT_DRAW_MAIN_END",
    "LV_EVENT_DRAW_POST_BEGIN",
    "LV_EVENT_DRAW_POST",
    "LV_EVENT_DRAW_POST_END",
    "LV_EVENT_DRAW_PART_BEGIN",
    "LV_EVENT_DRAW_PART_END",
    "LV_EVENT_VALUE_CHANGED",
    "LV_EVENT_INSERT",
    "LV_EVENT_REFRESH",
    "LV_EVENT_READY",
    "LV_EVENT_CANCEL",
    "LV_EVENT_DELETE",
    "LV_EVENT_CHILD_CHANGED",
    "LV_EVENT_CHILD_CREATED",
    "LV_EVENT_CHILD_DELETED",
    "LV_EVENT_SCREEN_UNLOAD_START",
    "LV_EVENT_SCREEN_LOAD_START",
    "LV_EVENT_SCREEN_LOADED",
    "LV_EVENT_SCREEN_UNLOADED",
    "LV_EVENT_SIZE_CHANGED",
    "LV_EVENT_STYLE_CHANGED",
    "LV_EVENT_LAYOUT_CHANGED",
    "LV_EVENT_GET_SELF_SIZE",
    "_LV_EVENT_LAST",
    "LV_EVENT_PREPROCESS"
};

void lv_event_print(lv_event_code_t event_code, const char* func_name)
{
    printf("%s call event_code: %s\n", func_name, event_code_list[event_code]);
}
void lv_key_code_print(lv_key_t key_code, const char* func_name)
{
    switch (key_code)
    {
    case LV_KEY_UP:
        printf("%s call key_code: LV_KEY_UP\n", func_name);
        break;
    case LV_KEY_DOWN:
        printf("%s call key_code: LV_KEY_DOWN\n", func_name);
        break;
    case LV_KEY_RIGHT:
        printf("%s call key_code: LV_KEY_RIGHT\n", func_name);
        break;
    case LV_KEY_LEFT:
        printf("%s call key_code: LV_KEY_LEFT\n", func_name);
        break;
    case LV_KEY_ESC:
        printf("%s call key_code: LV_KEY_ESC\n", func_name);
        break;
    case LV_KEY_DEL:
        printf("%s call key_code: LV_KEY_DEL\n", func_name);
        break;
    case LV_KEY_BACKSPACE:
        printf("%s call key_code: LV_KEY_BACKSPACE\n", func_name);
        break;
    case LV_KEY_ENTER:
        printf("%s call key_code: LV_KEY_ENTER\n", func_name);
        break;
    case LV_KEY_NEXT:
        printf("%s call key_code: LV_KEY_NEXT\n", func_name);
        break;
    case LV_KEY_PREV:
        printf("%s call key_code: LV_KEY_PREV\n", func_name);
        break;
    case LV_KEY_HOME:
        printf("%s call key_code: LV_KEY_HOME\n", func_name);
        break;
    case LV_KEY_END:
        printf("%s call key_code: LV_KEY_END\n", func_name);
        break;
    default:
        break;
    }
}

static void add_obj_and_children_to_group(lv_group_t* group, lv_obj_t* obj) {
	//lv_obj_get_child_cnt(obj);

	for (int i = 0; i < lv_obj_get_child_cnt(obj); ++i) {
		if (lv_obj_get_child(obj, i)->flags & LV_OBJ_FLAG_CLICKABLE)
		{
			lv_group_add_obj(group, lv_obj_get_child(obj, i));
		}
    }
    if (obj->flags & LV_OBJ_FLAG_CLICKABLE)
    {
        lv_group_add_obj(group, obj);
    }
}

void ui_screen_load_cb(lv_event_t * e)
{
	// Your code here
	//lv_group_get_obj_count(lv_group_get_default())
	lv_group_remove_all_objs(lv_group_get_default());


	add_obj_and_children_to_group(lv_group_get_default(), e->target);
	lv_group_set_editing(lv_group_get_default(), false);
}

void ui_editing_on(lv_event_t * e)
{
	// Your code here
	lv_group_set_editing(lv_group_get_default(), true);
}

void ui_editing_off(lv_event_t* e)
{
	// Your code here
	lv_group_set_editing(lv_group_get_default(), false);
}

void ui_screen_unload_cb(lv_event_t * e)
{
	// Your code here
	lv_group_set_editing(lv_group_get_default(), false);
	lv_group_remove_all_objs(lv_group_get_default());
}

void edit_mod(lv_event_t * e)
{
	// Your code here

}

void diff_obj_to_group(lv_event_t * e)
{
	// Your code here
}

void add_obj_to_group(lv_event_t * e)
{
	// Your code here
}

void into_obj(lv_event_t * e)
{
	// Your code here
	lv_group_remove_all_objs(lv_group_get_default());


	add_obj_and_children_to_group(lv_group_get_default(), e->target);
	lv_group_set_editing(lv_group_get_default(), false);
    lv_group_focus_obj(lv_obj_get_child(e->target, 0));
}

void exit_obj(lv_event_t * e)
{
	// Your code here
	lv_group_remove_all_objs(lv_group_get_default());
	lv_obj_t* parent_obj = lv_obj_get_parent(e->target);

    add_obj_and_children_to_group(lv_group_get_default(), parent_obj);
    lv_group_set_editing(lv_group_get_default(), false);
	lv_group_focus_obj(parent_obj);
}

void recode_btn_press(lv_event_t * e)
{
	// Your code here
	if (recoder_flag)
	{
        recoder_flag = 0;
        esp_event_post(APP_RECODER_EVENTS, EVENT_RECODER_STOP, NULL, 0, portMAX_DELAY);
        lv_label_set_text(ui_Screen2LabelLabel3, "start");
        lv_group_focus_freeze(lv_group_get_default(), false);
	} 
	else
	{
        recoder_flag = 1;
        esp_event_post(APP_RECODER_EVENTS, EVENT_RECODER_START, NULL, 0, portMAX_DELAY);
        lv_label_set_text(ui_Screen2LabelLabel3, "stop");
        lv_group_focus_freeze(lv_group_get_default(), true);
	}
}


void websocket_open(lv_event_t * e)
{
	esp_event_post(APP_WEBSOCKET_EVENTS, EVENT_SOCKET_OPEN, NULL, 0, portMAX_DELAY);
	// esp_event_post(APP_DISPLAY_EVENTS, EVENT_SCREEN_ACTIVATE, NULL, 0, portMAX_DELAY);
}

void websocket_close(lv_event_t * e)
{
	esp_event_post(APP_WEBSOCKET_EVENTS, EVENT_SOCKET_CLOSE, NULL, 0, portMAX_DELAY);
    // esp_event_post(APP_DISPLAY_EVENTS, EVENT_SCREEN_DISACTIVATE, NULL, 0, portMAX_DELAY);

}
