// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: whatsder

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xC9C1C1), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Screen1LabelLabel2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1LabelLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1LabelLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1LabelLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1LabelLabel2, "1");

    ui_Screen1ButtonButton1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1ButtonButton1, 100);
    lv_obj_set_height(ui_Screen1ButtonButton1, 50);
    lv_obj_set_x(ui_Screen1ButtonButton1, -53);
    lv_obj_set_y(ui_Screen1ButtonButton1, -82);
    lv_obj_set_align(ui_Screen1ButtonButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1ButtonButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1ButtonButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1ButtonButton2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1ButtonButton2, 100);
    lv_obj_set_height(ui_Screen1ButtonButton2, 50);
    lv_obj_set_x(ui_Screen1ButtonButton2, 56);
    lv_obj_set_y(ui_Screen1ButtonButton2, -78);
    lv_obj_set_align(ui_Screen1ButtonButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1ButtonButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1ButtonButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1ButtonButton7 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1ButtonButton7, 100);
    lv_obj_set_height(ui_Screen1ButtonButton7, 50);
    lv_obj_set_x(ui_Screen1ButtonButton7, -51);
    lv_obj_set_y(ui_Screen1ButtonButton7, 58);
    lv_obj_set_align(ui_Screen1ButtonButton7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1ButtonButton7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1ButtonButton7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1ButtonButton8 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1ButtonButton8, 100);
    lv_obj_set_height(ui_Screen1ButtonButton8, 50);
    lv_obj_set_x(ui_Screen1ButtonButton8, 57);
    lv_obj_set_y(ui_Screen1ButtonButton8, 61);
    lv_obj_set_align(ui_Screen1ButtonButton8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1ButtonButton8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen1ButtonButton8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
