// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: whatsder

#include "../ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0xC4BABA), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Screen6LabelLabel6 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Screen6LabelLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen6LabelLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen6LabelLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen6LabelLabel6, "32");

    ui_Screen6ButtonButton21 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Screen6ButtonButton21, 100);
    lv_obj_set_height(ui_Screen6ButtonButton21, 50);
    lv_obj_set_x(ui_Screen6ButtonButton21, -53);
    lv_obj_set_y(ui_Screen6ButtonButton21, -82);
    lv_obj_set_align(ui_Screen6ButtonButton21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen6ButtonButton21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen6ButtonButton21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen6ButtonButton22 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Screen6ButtonButton22, 100);
    lv_obj_set_height(ui_Screen6ButtonButton22, 50);
    lv_obj_set_x(ui_Screen6ButtonButton22, 56);
    lv_obj_set_y(ui_Screen6ButtonButton22, -78);
    lv_obj_set_align(ui_Screen6ButtonButton22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen6ButtonButton22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen6ButtonButton22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen6ButtonButton23 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Screen6ButtonButton23, 100);
    lv_obj_set_height(ui_Screen6ButtonButton23, 50);
    lv_obj_set_x(ui_Screen6ButtonButton23, -51);
    lv_obj_set_y(ui_Screen6ButtonButton23, 58);
    lv_obj_set_align(ui_Screen6ButtonButton23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen6ButtonButton23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen6ButtonButton23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen6ButtonButton24 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Screen6ButtonButton24, 100);
    lv_obj_set_height(ui_Screen6ButtonButton24, 50);
    lv_obj_set_x(ui_Screen6ButtonButton24, 57);
    lv_obj_set_y(ui_Screen6ButtonButton24, 61);
    lv_obj_set_align(ui_Screen6ButtonButton24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen6ButtonButton24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen6ButtonButton24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen6, ui_event_Screen6, LV_EVENT_ALL, NULL);

}
