// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: whatsder

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0xCDC0C0), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Screen3LabelLabel1 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3LabelLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3LabelLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen3LabelLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3LabelLabel1, "3");

    ui_Screen3ButtonButton3 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3ButtonButton3, 100);
    lv_obj_set_height(ui_Screen3ButtonButton3, 50);
    lv_obj_set_x(ui_Screen3ButtonButton3, -53);
    lv_obj_set_y(ui_Screen3ButtonButton3, -82);
    lv_obj_set_align(ui_Screen3ButtonButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3ButtonButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen3ButtonButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen3ButtonButton4 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3ButtonButton4, 100);
    lv_obj_set_height(ui_Screen3ButtonButton4, 50);
    lv_obj_set_x(ui_Screen3ButtonButton4, 56);
    lv_obj_set_y(ui_Screen3ButtonButton4, -78);
    lv_obj_set_align(ui_Screen3ButtonButton4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3ButtonButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen3ButtonButton4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen3ButtonButton5 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3ButtonButton5, 100);
    lv_obj_set_height(ui_Screen3ButtonButton5, 50);
    lv_obj_set_x(ui_Screen3ButtonButton5, -51);
    lv_obj_set_y(ui_Screen3ButtonButton5, 58);
    lv_obj_set_align(ui_Screen3ButtonButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3ButtonButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen3ButtonButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen3ButtonButton6 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3ButtonButton6, 100);
    lv_obj_set_height(ui_Screen3ButtonButton6, 50);
    lv_obj_set_x(ui_Screen3ButtonButton6, 57);
    lv_obj_set_y(ui_Screen3ButtonButton6, 61);
    lv_obj_set_align(ui_Screen3ButtonButton6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen3ButtonButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen3ButtonButton6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}
