// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: whatsder

#include "../ui.h"
uint8_t recoder_flag;


void ui_Screen2_screen_init(void)
{
    
    recoder_flag = 0;
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xCCC2C2), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Screen2Panelcontainer = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2Panelcontainer, 240);
    lv_obj_set_height(ui_Screen2Panelcontainer, 240);
    lv_obj_set_scroll_dir(ui_Screen2Panelcontainer, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Screen2Panelcontainer, lv_color_hex(0xE41111), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Screen2Panelcontainer, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Screen2Panelcontainer, lv_color_hex(0xECEAEA), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Screen2Panelcontainer, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Screen2PanelPanel3 = lv_obj_create(ui_Screen2Panelcontainer);
    lv_obj_set_width(ui_Screen2PanelPanel3, 200);
    lv_obj_set_height(ui_Screen2PanelPanel3, 50);
    lv_obj_set_x(ui_Screen2PanelPanel3, -10);
    lv_obj_set_y(ui_Screen2PanelPanel3, -10);
    lv_obj_add_flag(ui_Screen2PanelPanel3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen2PanelPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2PanelPanel3, lv_color_hex(0xDAD3D3), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Screen2PanelPanel3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Screen2LabelLabel5 = lv_label_create(ui_Screen2PanelPanel3);
    lv_obj_set_width(ui_Screen2LabelLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2LabelLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen2LabelLabel5, LV_ALIGN_CENTER);

    ui_Screen2PanelPanel1 = lv_obj_create(ui_Screen2Panelcontainer);
    lv_obj_set_width(ui_Screen2PanelPanel1, 200);
    lv_obj_set_height(ui_Screen2PanelPanel1, 50);
    lv_obj_set_x(ui_Screen2PanelPanel1, 20);
    lv_obj_set_y(ui_Screen2PanelPanel1, 46);
    lv_obj_add_flag(ui_Screen2PanelPanel1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Screen2PanelPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2PanelPanel1, lv_color_hex(0xD6CECE), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Screen2PanelPanel1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Screen2LabelLabel7 = lv_label_create(ui_Screen2PanelPanel1);
    lv_obj_set_width(ui_Screen2LabelLabel7, lv_pct(100));
    lv_obj_set_height(ui_Screen2LabelLabel7, lv_pct(100));
    lv_obj_set_align(ui_Screen2LabelLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2LabelLabel7,
                      "啊实打实大苏打实打实爱的阿斯顿啊打算打赏啊实打实大苏打实打实爱的阿斯顿啊打算打赏啊实打实大苏打实打实爱的阿斯顿啊打算打赏啊实打实大苏打实打实爱的阿斯顿啊打算打赏啊实打实大苏打实打实爱的阿斯顿啊打算打赏啊实打实大苏打实打实爱的阿斯顿啊打算打赏");
    lv_obj_set_style_text_font(ui_Screen2LabelLabel7, &ui_font_Chinease, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Screen2Panelrecode = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2Panelrecode, 240);
    lv_obj_set_height(ui_Screen2Panelrecode, 50);
    lv_obj_set_align(ui_Screen2Panelrecode, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_Screen2Panelrecode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2Panelrecode, lv_color_hex(0xDEDBDB), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Screen2Panelrecode, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Screen2LabelLabel3 = lv_label_create(ui_Screen2Panelrecode);
    lv_obj_set_width(ui_Screen2LabelLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2LabelLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen2LabelLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2LabelLabel3, "start");
    lv_obj_clear_flag(ui_Screen2LabelLabel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen2PanelPanel3, ui_event_Screen2PanelPanel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2PanelPanel1, ui_event_Screen2PanelPanel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2Panelcontainer, ui_event_Screen2Panelcontainer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2Panelrecode, ui_event_Screen2Panelrecode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
